export const userOnePermissions = {
  tbDashboard: false,
  tbProfile: false,
  tbProperties: false,
  editTb: false,
  travelerDashboard: true,
  travelerProfile: true,
  travelerSearchPref: true,
  signOut: true,
  reviewBusiness: true,
  isUserLoggedIn: true,
  travelExpertLogin: false,
  expertDashboard: false,
  expertProfile: false,
  expertCreateService: false,
  expertCreateProduct: false,
  expertEditPackage: false,
  expertEditProduct: false,
  expertSettings: false,
  expertPublicProfile: false,
};
export const userTwoPermissions = {
  tbDashboard: false,
  tbProfile: false,
  tbProperties: false,
  editTb: false,
  travelerDashboard: false,
  travelerProfile: false,
  travelerSearchPref: false,
  signOut: true,
  reviewBusiness: false,
  isUserLoggedIn: true,
  travelExpertLogin: false,
  expertDashboard: true,
  expertProfile: true,
  expertCreateService: true,
  expertCreateProduct: true,
  expertEditPackage: true,
  expertEditProduct: true,
  expertSettings: true,
  expertPublicProfile: true,
};
export const userThreePermissions = {
  tbDashboard: true,
  tbProfile: true,
  tbProperties: true,
  editTb: true,
  travelerDashboard: false,
  travelerProfile: false,
  travelerSearchPref: false,
  signOut: true,
  reviewBusiness: false,
  isUserLoggedIn: true,
  travelExpertLogin: false,
  expertDashboard: false,
  expertProfile: false,
  expertCreateService: false,
  expertCreateProduct: false,
  expertEditPackage: false,
  expertEditProduct: false,
  expertSettings: false,
  expertPublicProfile: false,
};
export const logoutPermissions = {
  tbDashboard: false,
  tbProfile: false,
  tbProperties: false,
  editTb: false,
  travelerDashboard: false,
  travelerProfile: false,
  travelerSearchPref: false,
  travelerLogin: true,
  tbLogin: true,
  signOut: false,
  reviewBusiness: false,
  isUserLoggedIn: false,
  travelExpertLogin: true,
  expertDashboard: false,
  expertProfile: false,
  expertCreateService: false,
  expertCreateProduct: false,
  expertEditPackage: false,
  expertEditProduct: false,
  expertSettings: false,
  expertPublicProfile: false,
};
